blueprint:
  name: IKEA Shortcut Button Test 

  domain: automation
  input:
    button:
      name: Button
      description: IKEA Shortcut Button
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
    config_single:
      name: Single Click Config
      description: Action to run
      default: []
      selector:
        action:
    config_double:
      name: Double Click Config
      description: Action to run
      default: []
      selector:
        action:
mode: restart
max_exceeded: silent

trigger:
  - domain: mqtt
    device_id: !input button
    type: action
    subtype: "off"
    trigger: device
  - domain: mqtt
    device_id: !input button
    type: action
    subtype: "on"
    trigger: device

action:
  - variables:
      command: "{{ trigger.payload }}"
  - choose:
      - conditions:
          - "{{ command == 'config_double' }}"
        sequence: !input config_double
      - conditions:
          - "{{ command == 'config_single' }}"
        sequence: !input config_single
