blueprint:
  name: IKEA Tradfri Shortcut Button (E1812)
  description: Control actions for the IKEA Tradfri Shortcut Button E1812 using Zigbee2MQTT and MQTT triggers.
  domain: automation
  input:
    remote:
      name: IKEA Tradfri Shortcut Button
      description: Select the button entity.
      selector:
        device:
          integration: mqtt
    single_press_action:
      name: Single Press Action
      description: Action to run on a single press.
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to run on a double press.
      default: []
      selector:
        action: {}
    long_press_action:
      name: Long Press Action
      description: Action to run on a long press.
      default: []
      selector:
        action: {}

trigger:
  - platform: mqtt
    topic: !input "remote"
    value_template: "{{ trigger.payload_json.action }}"
    payload: single
  - platform: mqtt
    topic: !input "remote"
    value_template: "{{ trigger.payload_json.action }}"
    payload: double
  - platform: mqtt
    topic: !input "remote"
    value_template: "{{ trigger.payload_json.action }}"
    payload: long

action:
  - choose:
      - conditions:
          - condition: trigger
            id: single
        sequence: !input "single_press_action"
      - conditions:
          - condition: trigger
            id: double
        sequence: !input "double_press_action"
      - conditions:
          - condition: trigger
            id: long
        sequence: !input "long_press_action"